name: hwinfo # you probably want to 'snapcraft register <name>'
version: '23.21' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run hwinfo # 79 char long summary
description: |
  snap to run hwinfo version 23.21.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    lsusb:
        command: usr/bin/hwinfo
        plugs: [hardware-observe]

parts:
    hwinfo:
#        source: http://archive.ubuntu.com/ubuntu/pool/universe/h/hwinfo/hwinfo_21.23.orig.tar.gz
        source: https://launchpad.net/ubuntu/+archive/primary/+files/hwinfo_21.38.orig.tar.gz
        source-type: tar
        plugin: make
        make-parameters: [hwinfo]
#        stage-packages:
#          - libhd-dev
#          - libhd-doc
#          - libhd21
        build-packages:
          - libhd-dev
          - libhd-doc
          - libhd21

