name: hwinfo # you probably want to 'snapcraft register <name>'
version: '23.21' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run hwinfo # 79 char long summary
description: |
  snap to run hwinfo version 23.21.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    hwinfo:
        command: usr/sbin/hwinfo
        plugs: [hardware-observe]

parts:
    hwinfo:
        plugin: dump
        source: .
        stage-packages:
           - hwinfo
        build-packages:
           - hwinfo

